1. This is a humongous commit. It is made after an ***unacceptably long*** gap.
        2.Most of the py files (except for those in Chapter 1 and Chapter 2) have been converted to JUPYTER NOTEBOOKS.
        These notebooks were  then modified to run. The last program in the book - Chapter 5/ptb_word_lm.py - has not been run

        3. Chapter 1 and Chapter 2 were run in the SPYDER IDE. Almost all the code has been run as python code from the terminal.
        Some changes needed to be made for python 3.6

        4. Modifications were needed as the programs were run using python 3. The versions of python and TensorFlow:

                (tensorflow) rm@ubuntu:~/Code-GettingStartedWithTF$ python
                Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
                [GCC 7.2.0] on linux
                Type "help", "copyright", "credits" or "license" for more information.
                >>> import tensorflow as tf
                >>> tf.__version__
                '1.8.0'

        5. The book code is actually meant for TensorFlow version 0.5 and Python 2.7. That has now been installed. Installation seems
        okay on preliminary check. This is what has been installed in the conda environment tensorflow-0.5-0

                (tensorflow-0.5-0) rm@ubuntu:~/Code-GettingStartedWithTF$ python
                Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 23:32:55)
                [GCC 7.2.0] on linux2
                Type "help", "copyright", "credits" or "license" for more information.
                >>> import tensorflow as tf
                >>> tf.__version__
                Traceback (most recent call last):
                  File "<stdin>", line 1, in <module>
                AttributeError: 'module' object has no attribute '__version__'
                >>>

                (tensorflow-0.5-0) rm@ubuntu:~/Code-GettingStartedWithTF$ conda list tensorflow
                * packages in environment at /home/rm/anaconda3/envs/tensorflow-0.5-0:
                *
                * Name                    Version                   Build  Channel
                tensorflow                0.5.0                     <pip>

        6. Modifications done to make the programs run in the environment (tensorflow), needed:
                * The modules to read MNIST to be changed.
                * Paths to be added to PYTHONPATH

        7. Its been a steep learning curve.

        8. I now want to run the code in the environment that the book intended it to run.
        That is because the last program - Chapter 5/ptb_word_lm.py - is hard to understand for making changes. I have made some.
        Those will need to be reversed. Also some of the changes made to the .py files would have to be reversed.
        Since the book did not use jupyter notebooks they need not be touched. In fact for the new environment they are
        superfluous and could be done be done away with.

        9. These are changes that are not to be merged into the master branch.
        Therefore, what is needed to be done is to commit and push to the remote repo.
        The remote repo is then to be forked for the purpose of working in the new environment (tensorflow-0.5-0)